### ISSUE TITLE
Use Google Trends for getting new words (Idea)

### ISSUE THREAD

**Issue by panmona** [tobihagemann/shitishot#6]
As an additional data source for words you could use Google Trends. There is an inofficial API for that: https://www.npmjs.com/package/google-trends-api which is intended to be used in Node.

PS: Really like the web version of this Neo Magazin game.

**Comment by tobihagemann** [comment]
Thank you for your suggestion, @maracuja-juice!

I wouldn't say that this would replace the current experimental Google service (which indeed uses web scraping for getting the number of search results). At least I don't know which metrics would be suitable for that. Did you have a specific metric from that API in mind?

But I think it could be a new source for words (in addition to Wikipedia). Even though I don't see how to get the trending searches with that API, I've seen in a Python library that it should be possible: https://github.com/GeneralMills/pytrends#trending-searches

**Comment by panmona** [comment]
Oh you're right. My bad 😅
But for getting new terms this could be (as you say) useful. I also wasn't able to find out though how 'trending topics' can be found via this API.
